---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
silent: true
includes:
  yaml: tasks/yaml.yml
  typst: tasks/typst.yml
tasks:
  default:
    desc: List tasks
    cmds:
      - task --list
  clean:
    desc: Clean build artifacts
    deps:
      - typst:clean
  build:
    desc: Build project
    deps:
      - typst:build
  watch:
    desc: Build project in watch mode
    deps:
      - typst:watch
  test:
    desc: Test project
    deps:
      - typst:test
  check:
    desc: Check project formatting
    deps:
      - yaml:check
      - typst:check
  fix:
    desc: Fix project formatting
    deps:
      - yaml:fix
      - typst:fix
